CREATE TABLE IF NOT EXISTS todos(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR NOT NULL,
    title VARCHAR(50) NOT NULL,
    detail VARCHAR(100),
    task_priority INTEGER DEFAULT 3 NOT NULL,
    deadline TIMESTAMP,
    task_status VARCHAR DEFAULT 'UNSTARTED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    deleted_at TIMESTAMP
);


CREATE TABLE IF NOT EXISTS users (
    id VARCHAR PRIMARY KEY,
    password VARCHAR NOT NULL
);